/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface FizHello {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface FizHelloAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface FizTimeAgo {
    'dateObj': Date;
  }
  interface FizTimeAgoAttributes extends StencilHTMLAttributes {
    'dateObj'?: Date;
  }
}

declare global {
  interface StencilElementInterfaces {
    'FizHello': Components.FizHello;
    'FizTimeAgo': Components.FizTimeAgo;
  }

  interface StencilIntrinsicElements {
    'fiz-hello': Components.FizHelloAttributes;
    'fiz-time-ago': Components.FizTimeAgoAttributes;
  }


  interface HTMLFizHelloElement extends Components.FizHello, HTMLStencilElement {}
  var HTMLFizHelloElement: {
    prototype: HTMLFizHelloElement;
    new (): HTMLFizHelloElement;
  };

  interface HTMLFizTimeAgoElement extends Components.FizTimeAgo, HTMLStencilElement {}
  var HTMLFizTimeAgoElement: {
    prototype: HTMLFizTimeAgoElement;
    new (): HTMLFizTimeAgoElement;
  };

  interface HTMLElementTagNameMap {
    'fiz-hello': HTMLFizHelloElement
    'fiz-time-ago': HTMLFizTimeAgoElement
  }

  interface ElementTagNameMap {
    'fiz-hello': HTMLFizHelloElement;
    'fiz-time-ago': HTMLFizTimeAgoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
